server:
  port: 18000
  servlet:
    context-path: /


system:
  config:
    websocket:
      server-properties:
        port: 18001
        event-path: /test1


#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    hisaige:
#      druid:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3316/hisaige_cloud_test1?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#        username: root
#        password: cyj515818
#        initialSize: 5
#        minIdle: 20
#        maxActive: 50
#        # 配置获取连接等待超时的时间
#        maxWait: 60000
#        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#        timeBetweenEvictionRunsMillis: 60000
#        # 配置一个连接在池中最小生存的时间，单位是毫秒
#        minEvictableIdleTimeMillis: 300000
#        #检验连接是否有效的查询语句。如果数据库Driver支持ping()方法，则优先使用ping()方法进行检查，否则使用validationQuery查询进行检查。(Oracle jdbc Driver目前不支持ping方法)
#        validationQuery: SELECT 1 FROM DUAL
#        #设置从连接池获取连接时是否检查连接有效性，true时，如果连接空闲时间超过minEvictableIdleTimeMillis进行检查，否则不检查;false时，不检查
#        testWhileIdle: true
#        #设置从连接池获取连接时是否检查连接有效性，true时，每次都检查;false时，不检查
#        testOnBorrow: false
#        #设置往连接池归还连接时是否检查连接有效性，true时，每次都检查;false时，不检查
#        testOnReturn: false
#        # 打开PSCache，并且指定每个连接上PSCache的大小
#        poolPreparedStatements: true
#        #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
#        maxPoolPreparedStatementPerConnectionSize: 20
#        # 合并多个DruidDataSource的监控数据
#        useGlobalDataSourceStat: true
#        #打开后，增强timeBetweenEvictionRunsMillis的周期性连接检查，minIdle内的空闲连接，每次检查强制验证连接有效性. 参考：https://github.com/alibaba/druid/wiki/KeepAlive_cn
#        #单位：秒，检测连接是否有效的超时时间。底层调用jdbc Statement对象的void setQueryTimeout(int seconds)方法
#        validationQueryTimeout: 1
#        #打开后，增强timeBetweenEvictionRunsMillis的周期性连接检查，minIdle内的空闲连接，每次检查强制验证连接有效性. 参考：https://github.com/alibaba/druid/wiki/KeepAlive_cn
#        keepAlive: true
#        #  配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#        filters: stat,wall
#        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#        #      # 配置监控服务器,目前下面这种配置在1.1.10可以，高版本比如1.1.16不行,
#        #      # 目前使用的是较高版本，所以先注释，使用DataSourceConfiguration中的注释代替
#        setting:
#          mapper-location: mybatis-mappers
#          mapper-package: "com.hisaige.db3.dao"
#          statViewServlet:
#            enable: true
#            username: admin
#            password: 123456
#            reset-enable: false
#            url-pattern: "/druid/*"
#            #         # 添加IP白名单，如果有多个则用逗号分隔，注意不能有空格,如果不包含127.0.0.1则本机只能用localhost访问
#            allow: "192.168.37.138,10.82.13.245"
#            # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
#            deny: "192.168.1.3"

  jackson:
    serialization:
      write-dates-as-timestamps: true

hisaige:
  system:
    config:
      enable-swagger2: true